#!/usr/bin/env bash
# Generate every agent surface from personas/*.md.
#
# Each agent mandates its own path and its own frontmatter, so the same body has
# to exist in ~15 places. That makes copies correct here — but hand-maintained
# copies drift, so nothing under a generated path is ever edited directly. Edit
# personas/*.md and re-run. `./test.sh` fails if any generated file is stale.
#
#   ./build.sh          write in place
#   ./build.sh OUTDIR   write into OUTDIR instead (used by test.sh to diff)
#   ./build.sh --list   print the generated paths, one per line
set -euo pipefail
cd "$(dirname "$0")"

# The manifest. test.sh walks this same list, so a new surface cannot be added
# without the staleness check covering it.
SURFACES=(
  AGENTS.md CLAUDE.md GEMINI.md gemini-extension.json
  .cursor/rules/on-point.mdc
  .windsurf/rules/on-point.md
  .clinerules/on-point.md
  .agents/rules/on-point.md
  .qoder/rules/on-point.md
  .kiro/steering/on-point.md
  .github/copilot-instructions.md
  .openclaw/skills/on-point/SKILL.md
  skills/on-point/SKILL.md
  .opencode/command/on-point.md
  .codex/config.toml .codex/hooks.json
  .codex-plugin/plugin.json .devin-plugin/plugin.json .qoder-plugin/plugin.json
)

if [ "${1:-}" = "--list" ]; then printf '%s\n' "${SURFACES[@]}"; exit 0; fi

OUT="${1:-.}"
BODY="$(cat personas/*.md)"
NAME="on-point"
DESC="Essence first, say less. Big idea first, then the one next action, in terse prose. Substance never compressed."
SHORT="Big idea first, then the next action, then say less."
REPO="https://github.com/HuskyDanny/OnPoint"
VER="$(python3 -c 'import json;print(json.load(open(".claude-plugin/plugin.json"))["version"])')"
MARK="<!-- GENERATED by ./build.sh from personas/*.md — edit those, not this file -->"

w() { # w <relpath>  — body on stdin
  local p="$OUT/$1"
  mkdir -p "$(dirname "$p")"
  cat > "$p"
}

# ── plain always-on rule files: the body, verbatim ────────────────────────────
for p in AGENTS.md CLAUDE.md GEMINI.md \
         .windsurf/rules/on-point.md \
         .clinerules/on-point.md \
         .agents/rules/on-point.md \
         .qoder/rules/on-point.md \
         .github/copilot-instructions.md; do
  { printf '%s\n\n%s\n' "$MARK" "$BODY"; } | w "$p"
done

# ── Cursor: .mdc, needs alwaysApply ──────────────────────────────────────────
{ printf -- '---\ndescription: %s\nglobs:\nalwaysApply: true\n---\n\n%s\n\n%s\n' \
    "$SHORT" "$MARK" "$BODY"; } | w .cursor/rules/on-point.mdc

# ── Kiro: steering, needs inclusion: always ──────────────────────────────────
{ printf -- '---\ntitle: On Point\ninclusion: always\n---\n\n%s\n\n%s\n' \
    "$MARK" "$BODY"; } | w .kiro/steering/on-point.md

# ── OpenClaw: a skill directory ──────────────────────────────────────────────
{ printf -- '---\nname: %s\ndescription: %s\n---\n\n%s\n\n%s\n' \
    "$NAME" "$DESC" "$MARK" "$BODY"; } | w .openclaw/skills/on-point/SKILL.md

# ── Claude Code: a skill, so /on-point works and Desktop can zip it ───────
{ printf -- '---\nname: %s\ndescription: %s Use when the user says "on point", "be terse", "abstract first", "say less", "next action first", or asks for less verbose output.\n---\n\n%s\n\n%s\n' \
    "$NAME" "$DESC" "$MARK" "$BODY"; } | w skills/on-point/SKILL.md

# ── OpenCode: a command ──────────────────────────────────────────────────────
{ printf -- '---\ndescription: %s\n---\n\n%s\n\n%s\n' \
    "$SHORT" "$MARK" "$BODY"; } | w .opencode/command/on-point.md

# ── Codex: enable hooks on both key spellings (old builds ignore unknown keys) ─
{ cat <<'TOML'
[features]
# codex-cli renamed codex_hooks -> hooks; builds that predate the rename ignore
# unknown keys silently, so shipping both activates on either.
hooks = true
codex_hooks = true
TOML
} | w .codex/config.toml

# Codex hooks take a shell command, so the payload must survive JSON quoting AND
# shell quoting. shlex.quote handles an apostrophe in the line; repr does not.
LINE="$(bash hooks/inject.sh --line)" python3 -c '
import json, os, shlex, sys
cmd = "echo " + shlex.quote(os.environ["LINE"])
json.dump({"hooks": {"SessionStart": [{"matcher": "startup|resume", "hooks": [
    {"type": "command", "command": cmd,
     "timeout": 5, "statusMessage": "Loading On Point"}]}]}}, sys.stdout, indent=2)
sys.stdout.write("\n")
' | w .codex/hooks.json

# ── Gemini extension manifest ────────────────────────────────────────────────
NAME="$NAME" DESC="$DESC" VER="$VER" python3 -c '
import json, os, sys
json.dump({"name": os.environ["NAME"], "version": os.environ["VER"],
           "description": os.environ["DESC"], "contextFileName": "GEMINI.md"},
          sys.stdout, indent=2)
sys.stdout.write("\n")
' | w gemini-extension.json

# ── Codex / Devin / Qoder plugin manifests ───────────────────────────────────
for host in codex devin qoder; do
  # Codex has its own hook file in its own shape; hooks/hooks.json is Claude Code's
  # (matcher regex + ${CLAUDE_PLUGIN_ROOT}), so pointing Codex at it would be a lie.
  hookfile="./hooks/hooks.json"
  [ "$host" = codex ] && hookfile="./.codex/hooks.json"
  NAME="$NAME" DESC="$DESC" VER="$VER" REPO="$REPO" HOOKFILE="$hookfile" python3 -c '
import json, os, sys
json.dump({
  "name": os.environ["NAME"], "version": os.environ["VER"],
  "description": os.environ["DESC"],
  "author": {"name": "Allen Pan", "url": "https://github.com/HuskyDanny"},
  "homepage": os.environ["REPO"], "repository": os.environ["REPO"],
  "license": "MIT",
  "keywords": ["terse", "adhd", "tokens", "productivity", "prompt"],
  "skills": "./skills/", "hooks": os.environ["HOOKFILE"],
  "interface": {
    "displayName": "On Point",
    "shortDescription": "Big idea first, then the next action, then say less",
    "longDescription": "Two axes on one switch: open at design altitude, put the one next action directly under it, and keep every word after that terse. Substance, exact errors and security are never compressed.",
    "developerName": "Allen Pan", "category": "Productivity",
    "capabilities": ["Instructions", "Lifecycle hooks"],
    "websiteURL": os.environ["REPO"],
    "defaultPrompt": ["Use On Point for this task.",
                      "Answer with the big idea first, then stop.",
                      "Give me the one next action, numbered if there are several."],
    "brandColor": "#111111"
  }}, sys.stdout, indent=2)
sys.stdout.write("\n")
' | w ".${host}-plugin/plugin.json"
done

if [ "$OUT" = "." ]; then
  echo "wrote $(printf '%s\n' "${SURFACES[@]}" | wc -l | tr -d ' ') agent surfaces from personas/*.md"
fi
